### ISSUE TITLE
Color, Theme, Type 관련 질문

### ISSUE THREAD

**Issue by theBettor** [Team-PATCH/Harmony-Android#23]
## 🤷‍♂️ Description
- pr 피드백 주신 부분에서 제목 위의 3가지 중복이라 지워달라고 하셨는데.. 생각해보니까 저도 색깔 같은 저런 것들을 따로 지정해준 기억이 없어서 아마 컴포즈를 사용하면서 제공하는 기본적인 것일까요? 일단은 그냥 지우려고 합니다 디자인시스템이 있으니까~

## 📸 Screenshots
![스크린샷 2024-11-05 오후 8 38 34](https://github.com/user-attachments/assets/1425e408-2c8f-4bff-b6a1-121967cb0517)

**Comment by agvber** [comment]
네 jetpack compose view 생성하면 자동으로 생성되는 걸로 알고 있어요!
